### ISSUE TITLE
A question about the use of scripts

### ISSUE THREAD

**Issue by securmat** [in9uz/VLANPWN#2]
Excellent work, but a question arises for those of us who are not versed in these tests: how do I know if they are successful, what output should I expect or what command can I then test to verify that I have been successful?

Could you add some screenshot of example of how to verify that they have been successful?

Thank you very much in advance.

**Comment by in9uz** [comment]
Hello. Thank you for the comment.
In general, I want to completely rebuild the tool "DoubleTagging.py ", which will now affect the configuration of your network interface so that any of your request (which you need) from the interface, with two tags at once. Because the current version of the script simply generates ICMP on 2 pulls on L2 (802.1Q Encapsulation)
Soon I will finalize the README, show the operation process, screenshots, etc. You need a little patience.
This also applies to the "DTP" script Hijacking.py"
